### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by voarsh2** [Xenxia/ProxmoxTool#1]
I am running default python 2 which doesn't seem to work on this? I haven't tested Python 3, but I don't want to install unnecessary stuff on the Hypervisor.

**Comment by Xenxia** [comment]
I would not pass my program to python2,
but I have tested to compile (if you can say that) in a binary that can be executed without python3
can you test it on your side ? and give me a feedback.
Thanks
[vm.zip](https://github.com/Xenxia/ProxmoxTools/files/6136830/vm.zip)
